# certbot certonly --agree-tos -m admin@warmwave.ru --webroot -w /var/www/html/warmwave.ru/ -d warmwave.ru

server {
    listen 80;
    server_name warmwave.ru www.warmwave.ru;
    root /var/www/html/warmwave.ru;
    return 301 https://warmwave.ru$request_uri;
}

server {
    listen 443 ssl;
    server_name warmwave.ru www.warmwave.ru;
    charset utf-8;
    root /var/www/html/warmwave.ru;
    index index.html;

    # Static content
    location ~* ^.+.(jpg|jpeg|gif|png|css|zip|tgz|gz|rar|bz2|doc|xls|exe|pdf|ppt|txt|tar|mid|midi|wav|mp3|bmp|flv|rtf|js|swf|iso)$ {
        root /var/www/html/warmwave.ru;
    }

    # SSL support
    ssl_certificate /etc/letsencrypt/live/warmwave.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/warmwave.ru/privkey.pem;
}